# Generated by Django 4.1.6 on 2025-02-16 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_location',
            fields=[
                ('locationid', models.AutoField(primary_key=True, serialize=False)),
                ('locationname', models.CharField(max_length=25)),
                ('districtid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.tbl_district')),
            ],
        ),
    ]
