# Generated by Django 4.1.6 on 2025-02-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_tbl_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_brand',
            fields=[
                ('brandid', models.AutoField(primary_key=True, serialize=False)),
                ('brandname', models.CharField(max_length=25)),
                ('brandimage', models.ImageField(upload_to='')),
            ],
        ),
    ]
