# Generated by Django 4.1.6 on 2025-02-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_tbl_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_category',
            fields=[
                ('categoryid', models.AutoField(primary_key=True, serialize=False)),
                ('categoryname', models.CharField(max_length=25)),
                ('categoryimage', models.ImageField(upload_to='')),
            ],
        ),
    ]
