# Generated by Django 4.1.6 on 2025-02-16 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_tbl_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_subcategory',
            fields=[
                ('subcategoryid', models.AutoField(primary_key=True, serialize=False)),
                ('subcategoryname', models.CharField(max_length=25)),
                ('image', models.ImageField(upload_to='')),
                ('categoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.tbl_category')),
            ],
        ),
    ]
