# Generated by Django 4.1.6 on 2025-02-17 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GuestApp', '0001_initial'),
        ('AdminApp', '0005_tbl_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_dealer',
            fields=[
                ('dealerid', models.AutoField(primary_key=True, serialize=False)),
                ('dealername', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=50)),
                ('contactno', models.BigIntegerField()),
                ('locationid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.tbl_location')),
                ('loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuestApp.tbl_login')),
            ],
        ),
    ]
