# Generated by Django 4.1.6 on 2025-02-19 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GuestApp', '0001_initial'),
        ('AdminApp', '0006_tbl_dealer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_staff',
            fields=[
                ('staffid', models.AutoField(primary_key=True, serialize=False)),
                ('staffname', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=50)),
                ('contactno', models.BigIntegerField()),
                ('categoryid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.tbl_category')),
                ('locationid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.tbl_location')),
                ('loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuestApp.tbl_login')),
            ],
        ),
    ]
