# Generated by Django 4.1.6 on 2025-02-19 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0007_tbl_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_product',
            fields=[
                ('productid', models.AutoField(primary_key=True, serialize=False)),
                ('productname', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=50)),
                ('price', models.BigIntegerField()),
                ('unit', models.CharField(max_length=25)),
                ('image', models.ImageField(upload_to='')),
                ('dealerprice', models.IntegerField(default=0)),
                ('brandid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.tbl_brand')),
                ('subcategoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.tbl_subcategory')),
            ],
        ),
    ]
