# Generated by Django 4.1.6 on 2025-02-19 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0008_tbl_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_stock',
            fields=[
                ('stockid', models.AutoField(primary_key=True, serialize=False)),
                ('stock', models.IntegerField(default=0)),
                ('Reorderlevel', models.IntegerField(default=0)),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.tbl_product')),
            ],
        ),
    ]
