# Generated by Django 4.1.6 on 2025-02-23 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AdminApp', '0009_tbl_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_requestmaster',
            fields=[
                ('requestmasterid', models.AutoField(primary_key=True, serialize=False)),
                ('deliverydate', models.DateField(null=True)),
                ('totalamount', models.IntegerField()),
                ('status', models.CharField(max_length=25)),
                ('dealerid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.tbl_dealer')),
            ],
        ),
    ]
