# Generated by Django 4.1.6 on 2025-02-23 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0009_tbl_stock'),
        ('StaffApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_requestdetails',
            fields=[
                ('requestid', models.AutoField(primary_key=True, serialize=False)),
                ('requestdate', models.DateField()),
                ('remark', models.CharField(max_length=25, null=True)),
                ('price', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=25)),
                ('quantity', models.IntegerField(null=True)),
                ('dealerquantity', models.IntegerField(null=True)),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.tbl_product')),
                ('requestmasterid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StaffApp.tbl_requestmaster')),
                ('staffid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.tbl_staff')),
            ],
        ),
    ]
