# Generated by Django 4.1.6 on 2025-02-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StaffApp', '0002_tbl_requestdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_salesmaster',
            fields=[
                ('salesmasterid', models.AutoField(primary_key=True, serialize=False)),
                ('salesdate', models.DateField()),
                ('totalamount', models.IntegerField()),
                ('billingno', models.IntegerField()),
            ],
        ),
    ]
