# Generated by Django 4.1.6 on 2025-02-23 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0009_tbl_stock'),
        ('StaffApp', '0003_tbl_salesmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_salesdetails',
            fields=[
                ('salesdetailsid', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('productamount', models.IntegerField()),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.tbl_product')),
                ('salesmasterid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StaffApp.tbl_salesmaster')),
                ('staffid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.tbl_staff')),
            ],
        ),
    ]
