# Generated by Django 4.1.6 on 2025-02-23 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0009_tbl_stock'),
        ('StaffApp', '0004_tbl_salesdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_purchasemaster',
            fields=[
                ('purchasemasterid', models.AutoField(primary_key=True, serialize=False)),
                ('purchasedate', models.DateField()),
                ('totalamount', models.IntegerField()),
                ('billno', models.IntegerField()),
                ('dealerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.tbl_dealer')),
            ],
        ),
    ]
