# Generated by Django 4.1.6 on 2025-02-23 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0009_tbl_stock'),
        ('StaffApp', '0005_tbl_purchasemaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_purchasedetails',
            fields=[
                ('purchasedetailsid', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('productprice', models.IntegerField()),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.tbl_product')),
                ('purchasemasterid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StaffApp.tbl_purchasemaster')),
                ('staffid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.tbl_staff')),
            ],
        ),
    ]
