# Generated by Django 4.1.6 on 2025-03-08 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StaffApp', '0006_tbl_purchasedetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_payment',
            fields=[
                ('paymentid', models.AutoField(primary_key=True, serialize=False)),
                ('Amount', models.IntegerField()),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=25)),
                ('purchasemasterid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StaffApp.tbl_purchasemaster')),
            ],
        ),
    ]
